### ISSUE TITLE
1-CreateSegments.bat　FileNotFoundError: [WinError 2] 指定されたファイルが見つかりません。

### ISSUE THREAD

**Issue by FUTABATSAK** [tsukumijima/Aivis#2]
1-CreateSegments.bat　実行時

_RemoteTraceback:
"""
Traceback (most recent call last):
  File "concurrent\futures\process.py", line 246, in _process_worker
  File "D:\voice\Aivis-Dataset\Aivis\demucs.py", line 137, in __ExtractVoicesMultiProcess
    demucs_audio(
  File "D:\voice\Aivis-Dataset\venv\lib\site-packages\stable_whisper\audio.py", line 146, in demucs_audio
    audio = torch.from_numpy(load_audio(audio, model.samplerate))
  File "D:\voice\Aivis-Dataset\venv\lib\site-packages\stable_whisper\audio.py", line 80, in load_audio
    ffmpeg.input(file, threads=0)
  File "D:\voice\Aivis-Dataset\venv\lib\site-packages\ffmpeg\_run.py", line 313, in run
    process = run_async(
  File "D:\voice\Aivis-Dataset\venv\lib\site-packages\ffmpeg\_run.py", line 284, in run_async
    return subprocess.Popen(
  File "subprocess.py", line 971, in __init__
  File "subprocess.py", line 1456, in _execute_child
FileNotFoundError: [WinError 2] 指定されたファイルが見つかりません。
"""

The above exception was the direct cause of the following exception:

wavファイルを配置後、ファイルが見つからないとでます。
解決策のご教示お願い致します。

**Comment by tsukumijima** [comment]
おそらく Aivis ではなく litagin さんのフォークである Aivis-Dataset をお使いだと思います。こちらでは今の所 Windows の積極的なサポートはしていませんので、そちらの Issue に投稿してください。

**Comment by FUTABATSAK** [comment]
申し訳ございません取り下げます
